version: '3'

services:
    postgres:
        image: postgres:15-bookworm
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
        networks:
            - default

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: macbot:2.0
        ports:
            - '8080:8080'
        volumes:
            - ./src:/app/src
        depends_on:
            - postgres
        networks:
            - default

networks:
    default:
        driver: bridge
